# Copyright (c) 2019-2024, The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

jobs:
  - job: check_codespell
    displayName: "codespell"
    pool:
      vmImage: "ubuntu-latest"
    container: khronosgroup/docker-images:openxr-sdk.20240412@sha256:e477137f8558565ac9173de8713a3e44d6d564ba042db9a20ff560eb4bfdeccc

    steps:
      - checkout: self
        lfs: true

      - script: ./checkCodespell
        displayName: Run Codespell script
